### ISSUE TITLE
Host build cannot run resulting binary as root after make.

### ISSUE THREAD

**Issue by hez** [LeToteTeam/input_event#13]
The following line sets the sticky bit on the resulting executable https://github.com/nerves-web-kiosk/input_event/blob/main/Makefile#L64 which means you cannot run your program as root.

Expected behaviour:

```
 $ <path to input_event>/input_event-0.4.1/priv/input_event /dev/input/event0
1.0.1raspberrypi-ts
J��L�/	56�9��:9\56qJq9����J^C
```

Actual Behaviour:

```
$ sudo <path to input_event>/input_event-0.4.1/priv/input_event /dev/input/event0
input_event: Unable to open /dev/input/event0: Permission denied
```

Work Around:

If you remove the sticky bit from the binary you can run the program as root.
```
chmod 0755 <path to input_event>/input_event-0.4.1/priv/input_event
```

**Comment by fhunleth** [comment]
@hez - Thanks for debugging this. 

I just looked into it a bit, and I think that all of the chmod/chown lines in the `Makefile` can be deleted. It seems like the better approach is to ask users to add themselves to the `input` group if they don't have access. @mobileoverlord Do you know anything about this from when you all were using it at Le Tote?

**Comment by hez** [comment]
That sounds like a reasonable approach to me 👍

**Comment by cfx** [comment]
Agree with @fhunleth regarding `chmod/chown` removal from the `Makefile`. Another problem related with it is that it creates dependency on askpass. This results in errors like:
```
==> input_event
mkdir -p /home/cfx/devel/expi/_build/dev/lib/input_event/priv
mkdir -p /home/cfx/devel/expi/_build/dev/lib/input_event/obj
cc -c -std=gnu99 -o /home/cfx/devel/expi/_build/dev/lib/input_event/obj/input_event.o src/input_event.c
cc /home/cfx/devel/expi/_build/dev/lib/input_event/obj/input_event.o  -o /home/cfx/devel/expi/_build/dev/lib/input_event/priv/input_event
# For host builds, setuid root the input_event binary so that it can read /dev/input/event*
SUDO_ASKPASS=/usr/bin/ssh-askpass sudo -- sh -c 'chown root:root /home/cfx/devel/expi/_build/dev/lib/input_event/priv/input_event; chmod +s /home/cfx/devel/expi/_build/dev/lib/input_event/priv/input_event'
sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
sudo: a password is required
make: *** [Makefile:64: /home/cfx/devel/expi/_build/dev/lib/input_event/priv/input_event] Error 1
```
if askpass is not installed (and it's not installed by default on many linux distros).

**Comment by fhunleth** [comment]
@cfx or @hez, could one of you send a PR? I still have merge permission on this project, so if either of you can make the change and test it, I'll take it the rest of the way and see if I can get an update posted on hex.

**Comment by cfx** [comment]
PR: https://github.com/nerves-web-kiosk/input_event/pull/14
