### ISSUE TITLE
Compiled Artifact Missing?

### ISSUE THREAD

**Issue by mmmries** [LeToteTeam/input_event#9]
I just added this to a blinky project to try to make use of keyboard inputs coming from a little 5-button joystick mounted on the [raspberry pi sense hat](https://www.raspberrypi.org/documentation/hardware/sense-hat/).

When I ssh into my device and run `InputEvent.enumerate()` I get back this error:

```
** (MatchError) no match of right hand side value: {:error, {:enoent, [{:erlang, :open_port, [{:spawn_executable, '/srv/erlang/lib/input_event-0.4.0/priv/input_event'}, [{:args, ["/dev/input/event0"]}, {:packet, 2}, :use_stdio, :binary, :exit_status]], []}, {InputEvent, :init, 1, [file: 'lib/input_event.ex', line: 49]}, {:gen_server, :init_it, 2, [file: 'gen_server.erl', line: 374]}, {:gen_server, :init_it, 6, [file: 'gen_server.erl', line: 342]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 249]}]}}
    (input_event 0.4.0) lib/input_event/enumerate.ex:20: InputEvent.Enumerate.get_info/1
    (elixir 1.10.3) lib/enum.ex:1396: Enum."-map/2-lists^map/1-0-"/2
** (EXIT from #PID<0.1179.0>) shell process exited with reason: an exception was raised:
    ** (ErlangError) Erlang error: :enoent
        :erlang.open_port({:spawn_executable, '/srv/erlang/lib/input_event-0.4.0/priv/input_event'}, [{:args, ["/dev/input/event0"]}, {:packet, 2}, :use_stdio, :binary, :exit_status])
        (input_event 0.4.0) lib/input_event.ex:49: InputEvent.init/1
        (stdlib 3.12.1) gen_server.erl:374: :gen_server.init_it/2
        (stdlib 3.12.1) gen_server.erl:342: :gen_server.init_it/6
        (stdlib 3.12.1) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

I try to `ls` the priv dir of the application, but there is no `priv` directory within that libraries compiled directory

```
iex(4)> :code.priv_dir(:input_event)
'/srv/erlang/lib/input_event-0.4.0/priv'
iex(5)> ls "/srv/erlang/lib/input_event-0.4.0"
ebin
```

DId I forget a configuration step? Or maybe there's a problem with `elixir_make` not compiling this when I run `MIX_TARGET=rpi3a mix firmware`?

**Comment by mmmries** [comment]
Well, I just did a `rm -rf _build` on my host machine, and then re-built the firmware and now everything is working 🤷‍♂️

Not sure why I didn't get the compiled C on my first build, but a simple clean and re-compile fixed it.

**Comment by fhunleth** [comment]
Not you. This project compiles to it's source directory which is a big no, no. It should be updated. I suspect that this project isn't being maintained. If it is, let me know and I'll send a PR. If no one responds and someone wants to maintain a fork, I'll send a PR to the new place if they want help with this.
